spring:
  datasource:
    url: ${DB2_URL:jdbc:db2://localhost:50000/B2BOPS}
    username: ${DB2_USERNAME:db2inst1}
    password: ${DB2_PASSWORD:password}
    driver-class-name: com.ibm.db2.jcc.DB2Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.DB2Dialect
        format_sql: true
  flyway:
    connect-retries: 3
    locations: ${APP_FLYWAY_LOCATIONS:${app.flyway-base-locations}}

app:
  runtime-mode: db2
  persistence-mode: jpa-flyway-db2
  flyway-base-locations: classpath:db/migration/db2
